version: '3.3'
services:
  orion-ops:
    image: registry.cn-hangzhou.aliyuncs.com/lijiahangmax/orion-ops:1.2.6
    ports:
      - 1022:22
      - 1080:80
    environment:
      - MYSQL_HOST=orion-ops-db
      - MYSQL_USER=orion
      - MYSQL_PASSWORD=Data@123456
      - REDIS_HOST=orion-ops-redis
      - REDIS_PASSWORD=Data@123456
      - SECRET_KEY=orion_ops
      - DEMO_MODE=false
    volumes:
      - /data/orion-ops-space/docker-volumes/root:/root
    depends_on:
      - orion-ops-db
      - orion-ops-redis
  orion-ops-db:
    image: registry.cn-hangzhou.aliyuncs.com/lijiahangmax/orion-ops-mysql:1.2.6
    privileged: true
    environment:
      - MYSQL_DATABASE=orion-ops
      - MYSQL_USER=orion
      - MYSQL_PASSWORD=Data@123456
      - MYSQL_ROOT_PASSWORD=Data@123456
    ports:
      - 13306:3306
    volumes:
      - /data/orion-ops-space/docker-volumes/mysql/var-lib-mysql:/var/lib/mysql
      - /data/orion-ops-space/docker-volumes/mysql/var-lib-mysql-files:/var/lib/mysql-files
      - /data/orion-ops-space/docker-volumes/mysql/etc-mysql:/etc/mysql
  orion-ops-redis:
    image: registry.cn-hangzhou.aliyuncs.com/lijiahangmax/orion-ops-redis:1.2.6
    privileged: true
    ports:
      - 16379:6379
    environment:
      - REDIS_PASSWORD=Data@123456
    volumes:
      - /data/orion-ops-space/docker-volumes/orion-ops-redis/data:/data
    command: sh -c "redis-server /usr/local/redis.conf --requirepass $${REDIS_PASSWORD}"
  orion-adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080